apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  {{- include "spring.labels" . | nindent 2 }}
spec:
  selector:
    matchLabels:
      app: music
  replicas: {{ .Values.pods.replica }}
  template:
    metadata:
      {{- include "spring.labels" . | nindent 6 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.pods.image }}:{{ .Values.pods.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
