kind: Service
apiVersion: v1
metadata:
  name: my-service
  {{- include "spring.labels" . | nindent 2 }}
spec:
  selector:
    app: music
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080

