apiVersion: v1
kind: Pod
metadata:
 name: nginx
 labels:
  app: nginx
spec:
 containers:
 - name: k8s-demo
   image: nginx:latest
   volumeMounts:
   - name: config-volume
     mountPath: /etc/config
   ports:
    - containerPort: 80
 volumes:
   - name: config-volume
     configMap:
       name: nginx-proxy

