apiVersion: v1
kind: Service
metadata:
 name: code-server_k8s_part2_51
spec:
 ports:
 - port: 80
   targetPort: 8080
 selector:
   app: code-server
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: yanivomc/code-server:latest
        imagePullPolicy: Always
        name: code-server
        env:
        - name: PASSWORD
          value: "1234567"
        volumeMounts:
        - mountPath: /workspace
          name: workspace

      volumes:
        - name: workspace
          hostPath:
            # directory location on host
            path: /tmp/workarea
