apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: redis-test
spec:
  volumes:
    - name: redis-persistent-storage
      emptyDir: {}
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 80
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
  - name: springapp
    image: yanivomc/spring-music:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /app/data