apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    env: app-test
spec:
  volumes:
    - name: app-storage
      emptyDir: {}
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    # ports:
    # - containerPort: 80
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  - name: app2
    image: yanivomc/spring-music:latest
    # ports:
    # - containerPort: 8080
    volumeMounts:
    - name: app-storage
      mountPath: /storage