cat service.yaml
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer