apiVersion: v1
kind: Service
metadata:
  name: web2
  labels:
    app: web2
spec:
  selector:
    app: web2
  type: NodePort
  ports:
  - nodePort: 31719
    port: 8080
    protocol: TCP
    targetPort: 8080
