apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-minikube
  name: hello-minikube
spec:
  type: NodePort
  selector:
    app: hello-minikube
  ports:
  - nodePort: 30721
    port: 8080
    protocol: TCP
    targetPort: 8080
