apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-minikube
  name: hello-minikube
spec:
  selector:
    matchLabels:
      app: hello-minikube
  replicas: 1 
  template: 
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 31239
